/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import DAO.UsuarioDAO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import View.AreaUsuario;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jrper
 */
public class Login extends javax.swing.JFrame {

    AreaUsuario enviartexto;
    private final LoginController Controller;

    /**
     * Creates new form UsuarioView
     */
    public Login() {
        initComponents();
        Controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        Jsenha = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();
        jEntrar = new javax.swing.JButton();
        jRecuperar = new javax.swing.JButton();
        jCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jToggleButton1.setText("jToggleButton1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela De Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        label1.setText("Email");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        Jsenha.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Jsenha.setText("Senha");
        getContentPane().add(Jsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.magenta, java.awt.Color.magenta, new java.awt.Color(153, 51, 255), new java.awt.Color(153, 51, 255)));
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 177, -1));

        jSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.magenta, java.awt.Color.magenta, new java.awt.Color(153, 51, 255), new java.awt.Color(153, 51, 255)));
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 177, 20));

        jEntrar.setBackground(new java.awt.Color(153, 51, 255));
        jEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jEntrar.setText("Entrar");
        jEntrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jRecuperar.setBackground(new java.awt.Color(153, 51, 255));
        jRecuperar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRecuperar.setText("Esqueci minha senha");
        jRecuperar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecuperarActionPerformed(evt);
            }
        });
        getContentPane().add(jRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 20));

        jCadastrar.setBackground(new java.awt.Color(153, 51, 255));
        jCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCadastrar.setText("Registra-se");
        jCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/pngegg (3).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 310, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/anexi-fundo-login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntrarActionPerformed

        UsuarioDAO dao = new UsuarioDAO();
       if (dao.CheckLoginADM(jEmail.getText(), jSenha.getText())) {
            new AreaADM().setVisible(true);
            this.dispose();
        } else if (dao.CheckLogin(jEmail.getText(), jSenha.getText())) {
            if (enviartexto == null) {
                enviartexto = new AreaUsuario();
                enviartexto.setVisible(true);
                enviartexto.recebendo(jEmail.getText());

            } else {
                enviartexto.setVisible(true);
                enviartexto.setState(AreaUsuario.NORMAL);
                enviartexto.recebendo(jEmail.getText());
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Dados incorretos");
        }

        //Controller.autenticar();
        //this.dispose();

    }//GEN-LAST:event_jEntrarActionPerformed

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed
        Controller.Cadastrar();
        this.dispose();
    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecuperarActionPerformed
        Controller.esqueciSenha();
        //new AlterarSenha().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public JLabel getJsenha() {
        return Jsenha;
    }

    public void setJsenha(JLabel Jsenha) {
        this.Jsenha = Jsenha;
    }

    public JTextField getjEmail() {
        return jEmail;
    }

    public void setjEmail(JTextField jEmail) {
        this.jEmail = jEmail;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jsenha;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JTextField jEmail;
    private javax.swing.JButton jEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jRecuperar;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
